### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by u0078867** [rmsouza01/siamxt#1]
A feedback about building it on Windows (Anaconda Python 64 bits).

However, had to change setup.py:
```py
os.environ['OPT'] = " ".join(flag for flag in opt.split() if flag != '-Wstrict-prototypes')
```
into:
```py
if opt is not None:
    os.environ['OPT'] = " ".join(flag for flag in opt.split() if flag != '-Wstrict-prototypes')
```

And `aux.py` name into `_aux.py`, since `aux` is not an allowed name in Windows.

**Comment by rmsouza01** [comment]
Thanks. Building on windows was always a pain. I will test and incorporate
your suggestions :)

**Comment by rmsouza01** [comment]
Incorporated your suggestion, but I don't have a Windows computer to test it. I hope it is working now.

**Comment by u0078867** [comment]
Thanks
