### ISSUE TITLE
Compatibility with python 3

### ISSUE THREAD

**Issue by alelopes** [rmsouza01/siamxt#2]
hello Roberto. I forked your project and added Python 3 compatibilities. I basically changed relative imports, one division and the cpp files. I tested in two python 3 installations. Test in more if you want.

The link is here: [https://github.com/alelopes/siamxt](https://github.com/alelopes/siamxt)

If you have any questions, you can comment here or talk to me on Whatsapp 😄 

Best,

**Comment by rmsouza01** [comment]
Hello Alexandre,

Thank you for your help! I merged your fork into the master branch. So far, it seems to be working for both Python 2 and 3 :), but I will keep doing tests.

Cheers,
Roberto
