### ISSUE TITLE
.gitignore that ignores checked-in files

### ISSUE THREAD

**Issue by artem-ogre** [rmsouza01/siamxt#4]
Hi Roberto,

First, big thank you for all the nice work on siamxt.

**Issue**
I had a WTF moment today after trying to include siamxt files as a part of a test repository. I turned out that some of the check-in source files are ignored. Namely this part of `.gitignore`:
```
max_tree_c_01.py
max_tree_alpha_aux.py
morph_tree_alpha_aux.py
```

These files are actually required for max-tree to be calculated, so maybe they should not be in the ignore-list?

**Comment by rmsouza01** [comment]
Hi Artem,

Thank you for reporting the issue. You are correct that those files shouldn't be listed on the .gitignore. The reason they were is that siamxt used to depend on SWIG, which generated those files. Now, with the SWIG dependency removed, those files shound't be ignored.

 I appreciate your feedback. Please let me know if there is anything else I can do. Unfortynately, siamxt is not a project that I am working actively on.
